config/routes.rb
Rails.application.routes.draw do
  
  get 'why-turtle', to: 'pages#about', as: 'why_turtle'
  get 'pricing', to: 'pages#pricing'
  # get 'contact', to: 'pages#contact'

  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :contacts, only: [:new, :create ]
  
  get '/contact', to: 'contacts#new', as: 'contact'
  get 'contacts/sent'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, validate: true
  # attribute :nickname,  captcha: true

  def headers
    { 
      to: "uroshni77@gmail.com", # change this to be the email you want sent to
      subject: "Podcasts Contact Form",
      from: "admin@yourdomain.com",  # change this to be the email it is coming from
      reply_to: %("#{name}" <#{email}>) 
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
      redirect_to action: :sent
        else
            flash.now[:error] = 'Could not send message'
            render :new, status: :unprocessable_entity
        end
    end

  def sent

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def pricing
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/sent.html.erb
<div class="rounded bg-white shadow p-6">
    <h1>Message Sent!</h1>
    <p>Nice job! You successfully sent me a message.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcasts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('Lovepik_com-401527901-tortoise.png') %>
  </head>

  <body>
    <main>
      <%= render "layouts/shared/navbar" %>
      <%= yield %>
      <%= render "layouts/shared/footer" %>
    </main>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
    
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0 text-center">
        <li>
            <%= link_to "Who We Are", root_path, class: "mr-4 hover:underline md:mr-6" %>
        </li>
        <li>
            <%= link_to "Why Turtle", why_turtle_path, class: "mr-4 hover:underline md:mr-6" %>
        </li>
        <li>

            <%= link_to "Pricing", pricing_path, class: "mr-4 hover:underline md:mr-6" %>
        </li>
        <li>
            <%= link_to "Contact", contact_path, class: "hover:underline" %>
        </li>
    </ul>

    <a class="nline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0" href="https://lovepik.com/images/png-anthropomorphic-animal.html">Our Turtle is from  Lovepik.com</a>
</footer>


<footer class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <%= image_tag "Lovepik_com-401527901-tortoise.png", class: 'w-100',
  style: 'max-width: 3rem;' %>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2022 Turtle Podcasts
     
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>


      

app/views/layouts/shared/_navbar.html.erb
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <%= link_to root_path do %>
      <%= image_tag "Lovepik_com-401527901-tortoise.png", class: 'w-100', style: 'max-width: 4rem;' %>
    <% end %>
    
    <%= link_to root_path do %>
      <span class="ml-3 text-xl">Turtle Podcast</span>
    <% end %>  
    
    
    <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
      <%= link_to "Who We Are", root_path, class: 'mr-5 hover:text-gray-900' %>
      <%= link_to "Why Turtle", why_turtle_path, class: 'mr-5 hover:text-gray-900' %>
      <%= link_to "Pricing", pricing_path, class: 'mr-5 hover:text-gray-900' %>
      <%= link_to "Contact", contact_path, class: 'mr-5 hover:text-gray-900' %>
    </nav>
    <%# <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Button
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button> %>
  </div>
</header>

app/views/pages/about.html.erb
<section>
  <div class=" flex flex-col items-center px-5 py-8 mx-auto max-w-7xl sm:px-6 lg:px-8">
    <div class="flex flex-col w-full max-w-3xl mx-auto prose text-center">
      <div class="w-full mx-auto text-justify ">
        <br>
        <h1>A podcast is a turtle not a rabbit</h1>
        <br>    

        <p>A simple definition is: a podcast is an audio programme that is made available for downloading or listening via the Internet.
        In the world that’s becoming faster and faster, the podcast format has become incredibly popular. There are two reasons for it:</p>
        <p>The first one is that podcasts are a sort of counterbalance for a busy life. Everything around us is crowded with information, mostly short ones. It’s what our smartphones enable and social media dictate - scrolling over endless posts that should be no longer than 50 characters or, in the case of a video, only 3 to 60 seconds long. On the other hand a podcast represents a meaningful conversation that you can submerge in, that can make you think, which is the main reason of its constant growing popularity.</p>

        <p>The second reason is that audio content allows the listener to multitask. A recent study showed that while 49% of podcast listening happens at home, 22% happens while driving, 11% at work, and 8% while exercising. Speaking of volume, according to data shared by Statista, almost 60% of all US consumers older than 12 listen to podcasts. See <a target="_blank"  href='https://www.statista.com/chart/14306/podcast-adoption' class="no-underline hover:underline ..."/> here</a> for other countries: </p>

        And it’s still rising...

        <p>We can see that these facts show that human beings are desperately trying to escape this bombardment of information, whenever they can, and dive into something more meaningful, like a human conversation, on a topic of our choice.</p>

        <p>Now that we stated the obvious - that podcasts are huge, but also why that is the case, let’s go to the not so obvious part, which should concern anyone who’s trying to get into podcasting himself.</p>

        <h3>ROI</h3>

        <p>Ah, the magic words… well, when they work. First of all we should say that a return on investment from podcasting is very much possible. So how can you get it?</p>

        <p>Here we don’t want to get into all the advice a google search will throw at you and endless agencies will state as self-explanatory. But to sum it up, it all comes down to promoting yourself, mostly through social media. That is fine, generally speaking. But the problem is most of this promotion will get your podcast back to the place from which your listeners are trying to escape from - social media and endless scrolling with very short content.</p>

        <p>Think about it, how well can a 30-second reel or a 50-character quote be the means to take you to an hour-long conversation? Now, I’m not saying you shouldn’t advertise your podcast on social media in any form or in any other way you can think of. What I’m saying is that “the experts” propose this to be a dominant way to market your podcast. Why? Because it’s the fastest way for people to hear about you. But is it?</p>

        <p>Let’s make a little comparison with the food industry… Imagine you're selling organic vegetables. It took you time and effort to grow it, it’s healthy, people can eat it for a long period of time and just have benefits from it. Now you decide to promote your organic vegetables and you think: what’s the fastest way to get it to people’s attention? Where can I find a lot of people looking for food? And you conclude: Let’s put it in a fast food restaurant! The traffic is great there, a lot of people will hear about my product.</p>

        <p>I hope the comparison between podcasting as a medium and social media struck a chord. So as with fast food, people don’t come to social media for the kind of content a podcast is. Of course, some people will get interested in your podcast through social media as some would notice organic products in McDonalds, but it’s not what most people are there for.</p>

        <p>The other problem that’s popping up when you market yourself on social media is how many people are actually following you? How many likes or views do you get regularly or, at the very best, what’s the most likes or views you’ve ever got? If you're very popular, or a bit famous then this is the way, but most people don’t have too many followers. Say you get 100 likes for a social media post - how many of those people would be interested in a topic of your podcast? Probably not more than 10. Maybe a few more would listen to an episode or two because you’re friends but that’s one time thing. And the most important thing, when you post another episode you’re not presenting it to new people, it’s the same 10 from before - you’re not gaining a new audience. Surely, If people share your podcast you can get more listeners but, again, unless some of the people sharing it are really popular or a bit famous, you can expect a steady decline in visibility of your post, the further it goes away from you.</p>

        <p>Now let’s see what is the inherently good way when trying to promote a podcast; the way that suits the form of a podcast as a medium. It’s a simple way, the one that works all around the internet, no matter what you do and that is:</p>

        <h2>Networking</h2>

        <p>We’ll use an example where your podcast is about golfing (or knitting). When you start, you will be getting some audience on your own. After a while, you should start networking - finding other podcasters that are interested in the similar topic as you and invite them to your show (or become a guest at theirs). When you get a fellow podcaster on your show to talk about what you both find interesting, both of you are instantly being presented to a completely new audience and most importantly, the audience that loves the topic of your podcast. So these are the people that you want to target and the same goes for your guest, he wants your audience. So you don’t have to worry about whether your guest will promote and share an episode he had with you. Of course he will, he’s in it, he wants to promote himself! So imagine, over a course of time, you have 10 or 20 guests like that and you get to be a guest on some other shows. The number of your listeners would grow slowly and steadily.</p>

        <p>This brings us back to our title - that podcast is a turtle, not a rabbit. And as we know from the story - slow and steady gets the message across first.</p>

        <p>If we keep in mind the things we said here and acknowledge that podcast is a long-form medium, when you plan investment in your podcast it should also be slow and steady. So the one thing you have to have is audio, because that’s what a podcast is, an audio programme. Everything else, you can essentially do without. But you can also get all in: fancy show notes, audiogramms, reels, a social media strategy (with every day posts), video version of a podcast (that could be done with 3 cameras), promotion, booking, high-profile guests paid to be on your show and many more. You can imagine how much would all that cost. There are many agencies that can do all or some of this for you and most of them will promise success, because their strategy is just what you need. However, if you understand a podcast as a medium you can see that most of this you don’t really need. It will help you somewhat but not nearly enough to compensate for what you invested. And after six months of that kind of expense, it’s very likely you’ll just quit podcasting. And it would be because of trying to be a rabbit, instead of a turtle - you know, the one who wins.</p>

        <p>So, in order to go slow and steady, the only thing you have to have is an audio recording. You can record it in many simple ways nowadays and some platforms will put it out there for you for a subscription type fee. However, you should be careful with audio quirks because there is a long list of them. As a podcast producer with sound engineering of 20 years as a background, I have to tell you that the amount of misconceptions about many aspects of audio files coming from these platforms as well as some production companies is astonishing! Some of the ignorance they show can get a good sound engineer somewhere between laughing and crying. Namely, they are trying the one-size-fits-all approach in taking care of your audio recording while at the same time every recording is done in a completely different environment, setup, file type, rate etc. The reason this is very important is not a technical one, but the fact that bad audio will wear down your listeners, making them tired of what they are listening to. And they might not even notice it’s because of what your audio is doing to their hearing apparatus (mostly brain), they could just think the conversation you have is not that great so they got tired of it.</p>

        <p>Not to contradict myself here, you can do the audio part in the cheapest way possible, just as you can with all the other stuff that accompanies a podcast. But remember, a podcast is an audio programme and it’s not a well designed social media post or nice show notes. So it kinda makes sense that a podcast itself is done properly, before everything else.</p>

        <p>The conclusion would be that if you’re into podcasting you should do it the sustainable way and a way that’s inherent to the medium you chose, like we explained. Basically, it comes down to audio - which a podcast is, and networking - the best and most adequate way of promoting your new found passion. And it should be just that - something you love to do. Because it will leave a mark on the conversations you will have and that will draw people to listen to you, for a long time. All the other things, you can choose and pick from or go with the option your budget allows.</p>
        
        
        <p>That's why we created our <b><%= link_to "pricing", pricing_path, class: 'no-underline hover:underline ...' %></b> to be in accord with what we've talked about here.</p>
        <br>    
      </div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20 flex-col items-center text-center">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Turtle Podcast Production</h1>
      <p class="lg:w-1/2 w-full leading-relaxed text-gray-900">
        Created more than 50 podcasts and 2000 episodes! 
        <hr>Take a listen to some of them:</p>
    </div>
    <div class="flex flex-wrap -m-4">

      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 1 --> 
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/0ZmrzYXtsx61bwZPmJbMh2?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>
      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 2 --> 
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/4lM9FI10nkYWLeR8Htj7oB?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>
      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 3 --> 
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/0DhcVaxkANydf1xYe39Qdh?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>
      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 4 -->           
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/4Lr2XV7wtLaFKhgbGYLZJe?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>
      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 5 -->         
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/1USLHvePYY6VChzpbYP9ea?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>
      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 6-->          
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/07IGQ8vokiwHEm5ghZOhPQ?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>
      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 7-->          
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3Sj58u9sPvUUXZITu38o5n?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>

      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 8-->          
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/5QCwWYcxWOceIbMTdTp6eG?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>

      <div class="xl:w-1/3 md:w-1/2 p-4">
        <div class="border border-gray-200 p-6 rounded-lg">
          <div class="inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
            
          </div>
<! -- 9-->          
          <iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3ctHEMQluwxFVdAu80JoEx?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

        </div>
      </div>

    </div>
    <%= link_to contact_path do %>
      <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Let's Talk!</button>
    <% end %> 
  </div>
</section>

app/views/pages/pricing.html.erb
<div class="text-center">
	<br>
	<h1 class="text-4xl">Podcasting is easy and affordable!</h1>
	<br>
	<h3 class="text-2xl">- If you work with the right people -</h3>
</div>

<div class=" flex flex-col items-center px-5 py-8 mx-auto max-w-7xl sm:px-6 lg:px-8">
   <div class="flex flex-col w-full max-w-3xl mx-auto prose text-center">
    	<div class="w-full mx-auto text-justify ">	
		
		<p>We have been creating podcasts for years and we have seen that there are many wrong ways to go with podcasting but only one right way. Check out our experience and takeaways here: 
			<em> <%= link_to "A podcast is a turtle not a rabbit.", why_turtle_path, class: 'no-underline hover:underline ...' %></em></p>

		<p>In short, podcast is an audio programme and we keep our services centered around that fact. Also, podcasts are all about storytelling - you tell stories about your life, your work, your ideas and get people into your world.</p>

		<p>Stories you tell ARE going to draw people to you and your business which WILL get you your ROI, connections, opportunities.</p>

		<p>That’s why podcasts should be simple, fun and easy to produce. Don’t spend too much time or money on it, enjoy creating them so your audience can enjoy listening to you. </p>

		<p class="text-center">And our services are designed to fit this approach:</p>
		
		</div>
	</div>
</div>

<section>
	  <div class="relative items-center w-full py-12 mx-auto md:px-12 lg:px-16 max-w-7xl">
    <div class="grid grid-cols-1 gap-12 text-center lg:gap-24 lg:grid-cols-3">
      <div>
        <div class="p-6 mx-auto">
          <span class="mb-8 text-base font-semibold tracking-widest text-blue-600 uppercase"> Pay Per Episode </span>

          <strong class="flex items-end justify-center mx-auto mt-4 mb-8 text-3xl font-black leading-none text-center text-gray-500 lg:text-4xl">
            $75
            <span class="text-sm"> /mo </span>
          </strong>
          <span class="mx-auto text-2xl font-semibold leading-none tracking-tighter text-neutral-600 lg:text-3xl"> Audio Production </span>
          <p class="mx-auto mt-12 text-base text-gray-500 lading-relaxed">
          	<em>Optional:</em> <br>
			<strong>Show notes - $30</strong> <br>
			<strong>Audiograms</strong> (audio-visual snippets) with quotes for social media promotion <strong>- $45</strong>
</p>
          <div class="mt-6">
            <a href="#" class="w-full items-center block px-10 py-3.5 text-base font-medium text-center text-blue-600 transition duration-500 ease-in-out transform border-2 border-white shadow-md rounded-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">All for $150</a>
          </div>
        </div>
      </div>
      <div>
        <div class="p-6 mx-auto">
          <span class="mb-8 text-base font-semibold tracking-widest text-blue-600 uppercase"> Pay Monthly </span>

          <strong class="flex items-end justify-center mx-auto mt-4 mb-8 text-3xl font-black leading-none text-center text-gray-500 lg:text-4xl">
            $250
            <span class="text-sm"> /mo </span>
          </strong>
          <span class="mx-auto text-2xl font-semibold leading-none tracking-tighter text-neutral-600 lg:text-3xl"> Audio Production </span>
          <p class="mx-auto mt-12 text-base text-gray-500 lading-relaxed">
          	<em>Optional:</em> <br>
			<strong>Show notes - $100</strong> <br>
			<strong>Audiograms</strong> (audio-visual snippets) with quotes for social media promotion <strong>- $150</strong>
          </p>
          <div class="mt-6">
            <a href="#" class="flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">All for $500</a>
          </div>
        </div>
      </div>
      <div>
        <div class="p-6 mx-auto">
          <span class="mb-8 text-base font-semibold tracking-widest text-blue-600 uppercase"> One Time Fee </span>

          <strong class="flex items-end justify-center mx-auto mt-4 mb-8 text-3xl font-black leading-none text-center text-gray-500 lg:text-4xl">
            $150
            <span class="text-sm"> /mo </span>
          </strong>
          <span class="mx-auto text-2xl font-semibold leading-none tracking-tighter text-neutral-600 lg:text-3xl"> Publishing and Audio Setup </span>
          <p class="mx-auto mt-12 text-base text-gray-500 lading-relaxed">
          	<em>Optional:</em> <br>
			<strong>Artwork Design - $50</strong> <br>
			<strong>Licensed Music - $50</strong>
          </p>
          <div class="mt-6">
            <a href="#" class="w-full items-center block px-10 py-3.5 text-base font-medium text-center text-blue-600 transition duration-500 ease-in-out transform border-2 border-white shadow-md rounded-xl focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">All for $250</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="text-center">
	<br>
	<p><em>Other services include:</em> video editing, transcription, booking shows, finding guests...</p>
	<br>
	<p>Or get <b><%= link_to "in touch", contact_path %></b> for a custom made service, we're open to any requests!</p>
	<br>
	<h3 class="text-2xl"></h3>
</div>